baseURL = "https://aswinkarthik.dev/"
languageCode = "en-us"
title = "Aswin's Site"
theme = "journal"
googleAnalytics = "UA-146772394-1"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"


[params]
    author = "Aswin Karthik"
    description = "Developer/Programmer/Software Engineer"
    githubUsername = "aswinkarthik"
    iconFont = "mono-social"
    enableGoogleAnalytics = true
    portrait = "aswinkarthik.jpg"
    tagline = ""
    paginate = 3
    copyright = "Copyright © 2019 aswinkarthik.dev"
[social]
	github = "https://www.github.com/aswinkarthik"


