baseURL = "https://aswinkarthik.dev/"
languageCode = "en-us"
title = "Aswin Karthik's Personal site"
theme = "hugo-cactus-theme-plus"

[params]
    author = "Aswin Karthik"
    description = "Programmer"
    iconFont = "mono-social"

[social]
	github = "https://www.github.com/aswinkarthik"